name: cashcow
description: "Point of Sale is perfect for dining restaurant"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  device_preview: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/food_menu/
    - assets/icons/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
